{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Bat_Optimaization",
      "provenance": [],
      "collapsed_sections": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/manan-arya/Major_Project/blob/pso%2B/Bat_Optimaization.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "q6BCFd47FTrq",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "import pandas as pd\n",
        "import numpy as np"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "J0Px3YowHXPK",
        "colab_type": "code",
        "outputId": "05d439c8-7264-4342-a047-691a11722b95",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 301
        }
      },
      "source": [
        "! pip install pyswarms\n",
        "import pyswarms as ps"
      ],
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Collecting pyswarms\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/0b/6f/42605c4e111a08a8fbaba953d0783c56ad2913ffa5959bdac53f649502a2/pyswarms-1.1.0-py2.py3-none-any.whl (96kB)\n",
            "\r\u001b[K     |███▍                            | 10kB 18.7MB/s eta 0:00:01\r\u001b[K     |██████▉                         | 20kB 6.0MB/s eta 0:00:01\r\u001b[K     |██████████▎                     | 30kB 7.4MB/s eta 0:00:01\r\u001b[K     |█████████████▋                  | 40kB 7.8MB/s eta 0:00:01\r\u001b[K     |█████████████████               | 51kB 6.5MB/s eta 0:00:01\r\u001b[K     |████████████████████▌           | 61kB 7.1MB/s eta 0:00:01\r\u001b[K     |███████████████████████▉        | 71kB 7.9MB/s eta 0:00:01\r\u001b[K     |███████████████████████████▎    | 81kB 8.5MB/s eta 0:00:01\r\u001b[K     |██████████████████████████████▊ | 92kB 7.8MB/s eta 0:00:01\r\u001b[K     |████████████████████████████████| 102kB 5.5MB/s \n",
            "\u001b[?25hRequirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyswarms) (0.16.0)\n",
            "Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from pyswarms) (1.4.1)\n",
            "Requirement already satisfied: matplotlib>=1.3.1 in /usr/local/lib/python3.6/dist-packages (from pyswarms) (3.2.1)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from pyswarms) (4.41.1)\n",
            "Requirement already satisfied: attrs in /usr/local/lib/python3.6/dist-packages (from pyswarms) (19.3.0)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from pyswarms) (1.18.5)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.1->pyswarms) (0.10.0)\n",
            "Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.1->pyswarms) (1.2.0)\n",
            "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.1->pyswarms) (2.4.7)\n",
            "Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.3.1->pyswarms) (2.8.1)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from cycler>=0.10->matplotlib>=1.3.1->pyswarms) (1.12.0)\n",
            "Installing collected packages: pyswarms\n",
            "Successfully installed pyswarms-1.1.0\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "bXPqS04nHcSw",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "url = \"https://raw.githubusercontent.com/saranshtaneja/genetic_major/master/fb_dataset.csv\"\n",
        "data = pd.read_csv(url)"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "t5N63P-5HdUU",
        "colab_type": "code",
        "outputId": "069c5e81-dc5e-41ed-cc6d-5737e339249b",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 426
        }
      },
      "source": [
        "data"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>facebook_post_id</th>\n",
              "      <th>dominant_color.histogram[0]</th>\n",
              "      <th>dominant_color.histogram[1]</th>\n",
              "      <th>dominant_color.histogram[2]</th>\n",
              "      <th>dominant_color.histogram[3]</th>\n",
              "      <th>dominant_color.histogram[4]</th>\n",
              "      <th>dominant_color.histogram[5]</th>\n",
              "      <th>dominant_color.histogram[6]</th>\n",
              "      <th>dominant_color.histogram[7]</th>\n",
              "      <th>dominant_color.histogram[8]</th>\n",
              "      <th>dominant_color.histogram[9]</th>\n",
              "      <th>dominant_color.value</th>\n",
              "      <th>face_detection.average_face2frame_ratio</th>\n",
              "      <th>face_detection.average_face_count_per_frame</th>\n",
              "      <th>face_detection.average_face_present</th>\n",
              "      <th>general.duration</th>\n",
              "      <th>general.fps</th>\n",
              "      <th>general.frame_count</th>\n",
              "      <th>general.frame_size.height</th>\n",
              "      <th>general.frame_size.width</th>\n",
              "      <th>other.average_movie_speed</th>\n",
              "      <th>other.clutter_metric</th>\n",
              "      <th>rigidity.average_rigidity</th>\n",
              "      <th>shot_detection.average_shot_length</th>\n",
              "      <th>shot_detection.shots_count</th>\n",
              "      <th>shot_detection.transition_histogram[0]</th>\n",
              "      <th>shot_detection.transition_histogram[1]</th>\n",
              "      <th>text_detection.average_text2frame_ratio</th>\n",
              "      <th>text_detection.average_text_frames</th>\n",
              "      <th>title.sentiment</th>\n",
              "      <th>views.1</th>\n",
              "      <th>shares.1</th>\n",
              "      <th>comments.1</th>\n",
              "      <th>likes.1</th>\n",
              "      <th>views.2</th>\n",
              "      <th>shares.2</th>\n",
              "      <th>comments.2</th>\n",
              "      <th>likes.2</th>\n",
              "      <th>views.3</th>\n",
              "      <th>shares.3</th>\n",
              "      <th>...</th>\n",
              "      <th>views.159</th>\n",
              "      <th>shares.159</th>\n",
              "      <th>comments.159</th>\n",
              "      <th>likes.159</th>\n",
              "      <th>views.160</th>\n",
              "      <th>shares.160</th>\n",
              "      <th>comments.160</th>\n",
              "      <th>likes.160</th>\n",
              "      <th>views.161</th>\n",
              "      <th>shares.161</th>\n",
              "      <th>comments.161</th>\n",
              "      <th>likes.161</th>\n",
              "      <th>views.162</th>\n",
              "      <th>shares.162</th>\n",
              "      <th>comments.162</th>\n",
              "      <th>likes.162</th>\n",
              "      <th>views.163</th>\n",
              "      <th>shares.163</th>\n",
              "      <th>comments.163</th>\n",
              "      <th>likes.163</th>\n",
              "      <th>views.164</th>\n",
              "      <th>shares.164</th>\n",
              "      <th>comments.164</th>\n",
              "      <th>likes.164</th>\n",
              "      <th>views.165</th>\n",
              "      <th>shares.165</th>\n",
              "      <th>comments.165</th>\n",
              "      <th>likes.165</th>\n",
              "      <th>views.166</th>\n",
              "      <th>shares.166</th>\n",
              "      <th>comments.166</th>\n",
              "      <th>likes.166</th>\n",
              "      <th>views.167</th>\n",
              "      <th>shares.167</th>\n",
              "      <th>comments.167</th>\n",
              "      <th>likes.167</th>\n",
              "      <th>shares.168</th>\n",
              "      <th>comments.168</th>\n",
              "      <th>likes.168</th>\n",
              "      <th>views.168</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>407570359384477_612049142269930</td>\n",
              "      <td>0.002330</td>\n",
              "      <td>0.285182</td>\n",
              "      <td>0.321528</td>\n",
              "      <td>0.191053</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.007922</td>\n",
              "      <td>0.093197</td>\n",
              "      <td>0.098788</td>\n",
              "      <td>2</td>\n",
              "      <td>0.015108</td>\n",
              "      <td>0.251165</td>\n",
              "      <td>0.243243</td>\n",
              "      <td>85.840000</td>\n",
              "      <td>25</td>\n",
              "      <td>2146</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>1.680012</td>\n",
              "      <td>0.161410</td>\n",
              "      <td>0.212954</td>\n",
              "      <td>4.517895</td>\n",
              "      <td>19</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.054041</td>\n",
              "      <td>0.446412</td>\n",
              "      <td>4.651</td>\n",
              "      <td>21057</td>\n",
              "      <td>370</td>\n",
              "      <td>69</td>\n",
              "      <td>652</td>\n",
              "      <td>36707</td>\n",
              "      <td>619</td>\n",
              "      <td>105</td>\n",
              "      <td>1000</td>\n",
              "      <td>48639</td>\n",
              "      <td>796</td>\n",
              "      <td>...</td>\n",
              "      <td>350437</td>\n",
              "      <td>4913</td>\n",
              "      <td>376</td>\n",
              "      <td>4223</td>\n",
              "      <td>350504</td>\n",
              "      <td>4914</td>\n",
              "      <td>376</td>\n",
              "      <td>4223</td>\n",
              "      <td>350577</td>\n",
              "      <td>4915</td>\n",
              "      <td>376</td>\n",
              "      <td>4223</td>\n",
              "      <td>350642</td>\n",
              "      <td>4915</td>\n",
              "      <td>376</td>\n",
              "      <td>4223</td>\n",
              "      <td>350716</td>\n",
              "      <td>4916</td>\n",
              "      <td>376</td>\n",
              "      <td>4223</td>\n",
              "      <td>350785</td>\n",
              "      <td>4916</td>\n",
              "      <td>376</td>\n",
              "      <td>4223</td>\n",
              "      <td>350858</td>\n",
              "      <td>4916</td>\n",
              "      <td>376</td>\n",
              "      <td>4224</td>\n",
              "      <td>350942</td>\n",
              "      <td>4916</td>\n",
              "      <td>376</td>\n",
              "      <td>4225</td>\n",
              "      <td>351045</td>\n",
              "      <td>4916</td>\n",
              "      <td>376</td>\n",
              "      <td>4225</td>\n",
              "      <td>4916</td>\n",
              "      <td>376</td>\n",
              "      <td>4225</td>\n",
              "      <td>351137</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>407570359384477_612108412264003</td>\n",
              "      <td>0.005907</td>\n",
              "      <td>0.463291</td>\n",
              "      <td>0.059072</td>\n",
              "      <td>0.192405</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.093671</td>\n",
              "      <td>0.157806</td>\n",
              "      <td>0.027848</td>\n",
              "      <td>1</td>\n",
              "      <td>0.009970</td>\n",
              "      <td>0.304641</td>\n",
              "      <td>0.098734</td>\n",
              "      <td>47.400000</td>\n",
              "      <td>25</td>\n",
              "      <td>1185</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>15.270662</td>\n",
              "      <td>0.106316</td>\n",
              "      <td>0.270886</td>\n",
              "      <td>3.950000</td>\n",
              "      <td>12</td>\n",
              "      <td>0.833333</td>\n",
              "      <td>0.166667</td>\n",
              "      <td>0.052529</td>\n",
              "      <td>0.451477</td>\n",
              "      <td>4.566</td>\n",
              "      <td>15618</td>\n",
              "      <td>168</td>\n",
              "      <td>27</td>\n",
              "      <td>475</td>\n",
              "      <td>22384</td>\n",
              "      <td>246</td>\n",
              "      <td>33</td>\n",
              "      <td>690</td>\n",
              "      <td>24171</td>\n",
              "      <td>292</td>\n",
              "      <td>...</td>\n",
              "      <td>87968</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>87998</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88020</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88029</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88042</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88066</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88094</td>\n",
              "      <td>578</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88110</td>\n",
              "      <td>579</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88128</td>\n",
              "      <td>579</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>579</td>\n",
              "      <td>61</td>\n",
              "      <td>1617</td>\n",
              "      <td>88149</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>407570359384477_612000682274776</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.377131</td>\n",
              "      <td>0.072443</td>\n",
              "      <td>0.093750</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.197443</td>\n",
              "      <td>0.125000</td>\n",
              "      <td>0.134233</td>\n",
              "      <td>1</td>\n",
              "      <td>0.014187</td>\n",
              "      <td>0.171165</td>\n",
              "      <td>0.171165</td>\n",
              "      <td>56.320000</td>\n",
              "      <td>25</td>\n",
              "      <td>1408</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>4.000194</td>\n",
              "      <td>0.188503</td>\n",
              "      <td>0.387074</td>\n",
              "      <td>4.693333</td>\n",
              "      <td>12</td>\n",
              "      <td>0.750000</td>\n",
              "      <td>0.250000</td>\n",
              "      <td>0.084811</td>\n",
              "      <td>0.714489</td>\n",
              "      <td>3.721</td>\n",
              "      <td>2</td>\n",
              "      <td>81</td>\n",
              "      <td>67</td>\n",
              "      <td>329</td>\n",
              "      <td>35031</td>\n",
              "      <td>109</td>\n",
              "      <td>83</td>\n",
              "      <td>437</td>\n",
              "      <td>41947</td>\n",
              "      <td>123</td>\n",
              "      <td>...</td>\n",
              "      <td>116446</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116454</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116462</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116479</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116504</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116521</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116545</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116570</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116582</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>329</td>\n",
              "      <td>170</td>\n",
              "      <td>1193</td>\n",
              "      <td>116597</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>407570359384477_612254708916040</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.592656</td>\n",
              "      <td>0.144475</td>\n",
              "      <td>0.079272</td>\n",
              "      <td>0.072066</td>\n",
              "      <td>0.012697</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.097117</td>\n",
              "      <td>0.001716</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>1</td>\n",
              "      <td>0.006673</td>\n",
              "      <td>0.067605</td>\n",
              "      <td>0.066575</td>\n",
              "      <td>116.560000</td>\n",
              "      <td>25</td>\n",
              "      <td>2914</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>5.159395</td>\n",
              "      <td>0.098545</td>\n",
              "      <td>0.355525</td>\n",
              "      <td>5.067826</td>\n",
              "      <td>23</td>\n",
              "      <td>0.739130</td>\n",
              "      <td>0.260870</td>\n",
              "      <td>0.035462</td>\n",
              "      <td>0.315717</td>\n",
              "      <td>3.851</td>\n",
              "      <td>89140</td>\n",
              "      <td>4407</td>\n",
              "      <td>235</td>\n",
              "      <td>3486</td>\n",
              "      <td>213383</td>\n",
              "      <td>9438</td>\n",
              "      <td>402</td>\n",
              "      <td>6044</td>\n",
              "      <td>347713</td>\n",
              "      <td>14571</td>\n",
              "      <td>...</td>\n",
              "      <td>18606897</td>\n",
              "      <td>464169</td>\n",
              "      <td>7616</td>\n",
              "      <td>121156</td>\n",
              "      <td>18613170</td>\n",
              "      <td>464233</td>\n",
              "      <td>7616</td>\n",
              "      <td>121198</td>\n",
              "      <td>18619570</td>\n",
              "      <td>464290</td>\n",
              "      <td>7619</td>\n",
              "      <td>121244</td>\n",
              "      <td>18626146</td>\n",
              "      <td>464343</td>\n",
              "      <td>7622</td>\n",
              "      <td>121288</td>\n",
              "      <td>18632836</td>\n",
              "      <td>464385</td>\n",
              "      <td>7624</td>\n",
              "      <td>121330</td>\n",
              "      <td>18638793</td>\n",
              "      <td>464418</td>\n",
              "      <td>7626</td>\n",
              "      <td>121367</td>\n",
              "      <td>18643654</td>\n",
              "      <td>464447</td>\n",
              "      <td>7627</td>\n",
              "      <td>121397</td>\n",
              "      <td>18647758</td>\n",
              "      <td>464489</td>\n",
              "      <td>7628</td>\n",
              "      <td>121419</td>\n",
              "      <td>18651565</td>\n",
              "      <td>464539</td>\n",
              "      <td>7631</td>\n",
              "      <td>121442</td>\n",
              "      <td>464591</td>\n",
              "      <td>7633</td>\n",
              "      <td>121472</td>\n",
              "      <td>18655415</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>407570359384477_612167392258105</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.116180</td>\n",
              "      <td>0.436074</td>\n",
              "      <td>0.154377</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.293369</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>2</td>\n",
              "      <td>0.008844</td>\n",
              "      <td>0.094430</td>\n",
              "      <td>0.094430</td>\n",
              "      <td>75.400000</td>\n",
              "      <td>25</td>\n",
              "      <td>1885</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>5.295101</td>\n",
              "      <td>0.109216</td>\n",
              "      <td>0.611141</td>\n",
              "      <td>4.712500</td>\n",
              "      <td>16</td>\n",
              "      <td>0.812500</td>\n",
              "      <td>0.187500</td>\n",
              "      <td>0.049729</td>\n",
              "      <td>0.327321</td>\n",
              "      <td>4.901</td>\n",
              "      <td>17304</td>\n",
              "      <td>240</td>\n",
              "      <td>127</td>\n",
              "      <td>233</td>\n",
              "      <td>26215</td>\n",
              "      <td>355</td>\n",
              "      <td>176</td>\n",
              "      <td>337</td>\n",
              "      <td>29539</td>\n",
              "      <td>438</td>\n",
              "      <td>...</td>\n",
              "      <td>432502</td>\n",
              "      <td>6536</td>\n",
              "      <td>1032</td>\n",
              "      <td>1513</td>\n",
              "      <td>432868</td>\n",
              "      <td>6541</td>\n",
              "      <td>1032</td>\n",
              "      <td>1514</td>\n",
              "      <td>433204</td>\n",
              "      <td>6543</td>\n",
              "      <td>1032</td>\n",
              "      <td>1515</td>\n",
              "      <td>433517</td>\n",
              "      <td>6548</td>\n",
              "      <td>1032</td>\n",
              "      <td>1515</td>\n",
              "      <td>433862</td>\n",
              "      <td>6556</td>\n",
              "      <td>1032</td>\n",
              "      <td>1516</td>\n",
              "      <td>434279</td>\n",
              "      <td>6565</td>\n",
              "      <td>1033</td>\n",
              "      <td>1517</td>\n",
              "      <td>434799</td>\n",
              "      <td>6573</td>\n",
              "      <td>1033</td>\n",
              "      <td>1517</td>\n",
              "      <td>435447</td>\n",
              "      <td>6581</td>\n",
              "      <td>1035</td>\n",
              "      <td>1517</td>\n",
              "      <td>436017</td>\n",
              "      <td>6589</td>\n",
              "      <td>1035</td>\n",
              "      <td>1517</td>\n",
              "      <td>6597</td>\n",
              "      <td>1035</td>\n",
              "      <td>1517</td>\n",
              "      <td>436438</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1815</th>\n",
              "      <td>210277954204_10153191547364205</td>\n",
              "      <td>0.001443</td>\n",
              "      <td>0.107010</td>\n",
              "      <td>0.107611</td>\n",
              "      <td>0.088133</td>\n",
              "      <td>0.000120</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.056631</td>\n",
              "      <td>0.639053</td>\n",
              "      <td>9</td>\n",
              "      <td>0.015620</td>\n",
              "      <td>0.447878</td>\n",
              "      <td>0.446315</td>\n",
              "      <td>286.793103</td>\n",
              "      <td>29</td>\n",
              "      <td>8317</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>0.884065</td>\n",
              "      <td>0.108540</td>\n",
              "      <td>0.653361</td>\n",
              "      <td>22.061008</td>\n",
              "      <td>13</td>\n",
              "      <td>0.846154</td>\n",
              "      <td>0.153846</td>\n",
              "      <td>0.019021</td>\n",
              "      <td>0.242756</td>\n",
              "      <td>4.698</td>\n",
              "      <td>2365</td>\n",
              "      <td>54</td>\n",
              "      <td>14</td>\n",
              "      <td>88</td>\n",
              "      <td>4844</td>\n",
              "      <td>82</td>\n",
              "      <td>18</td>\n",
              "      <td>137</td>\n",
              "      <td>6327</td>\n",
              "      <td>106</td>\n",
              "      <td>...</td>\n",
              "      <td>17037</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17037</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17037</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17038</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17039</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17040</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17040</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17041</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17043</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>242</td>\n",
              "      <td>45</td>\n",
              "      <td>351</td>\n",
              "      <td>17044</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1816</th>\n",
              "      <td>210277954204_10153191554684205</td>\n",
              "      <td>0.000157</td>\n",
              "      <td>0.008956</td>\n",
              "      <td>0.154608</td>\n",
              "      <td>0.236704</td>\n",
              "      <td>0.367586</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.025297</td>\n",
              "      <td>0.206693</td>\n",
              "      <td>4</td>\n",
              "      <td>0.009507</td>\n",
              "      <td>0.268914</td>\n",
              "      <td>0.268914</td>\n",
              "      <td>438.931034</td>\n",
              "      <td>29</td>\n",
              "      <td>12729</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>0.828587</td>\n",
              "      <td>0.137349</td>\n",
              "      <td>0.847671</td>\n",
              "      <td>20.901478</td>\n",
              "      <td>21</td>\n",
              "      <td>0.761905</td>\n",
              "      <td>0.238095</td>\n",
              "      <td>0.004168</td>\n",
              "      <td>0.036452</td>\n",
              "      <td>4.425</td>\n",
              "      <td>6627</td>\n",
              "      <td>52</td>\n",
              "      <td>26</td>\n",
              "      <td>85</td>\n",
              "      <td>12010</td>\n",
              "      <td>71</td>\n",
              "      <td>40</td>\n",
              "      <td>124</td>\n",
              "      <td>14570</td>\n",
              "      <td>82</td>\n",
              "      <td>...</td>\n",
              "      <td>68520</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>490</td>\n",
              "      <td>68531</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>490</td>\n",
              "      <td>68545</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>490</td>\n",
              "      <td>68557</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>68570</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>68589</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>68607</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>68614</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>68623</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>511</td>\n",
              "      <td>163</td>\n",
              "      <td>491</td>\n",
              "      <td>68636</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1817</th>\n",
              "      <td>210277954204_10153191559204205</td>\n",
              "      <td>0.000625</td>\n",
              "      <td>0.020410</td>\n",
              "      <td>0.096741</td>\n",
              "      <td>0.114027</td>\n",
              "      <td>0.000417</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.024367</td>\n",
              "      <td>0.743414</td>\n",
              "      <td>9</td>\n",
              "      <td>0.011690</td>\n",
              "      <td>0.307092</td>\n",
              "      <td>0.305842</td>\n",
              "      <td>331.137931</td>\n",
              "      <td>29</td>\n",
              "      <td>9603</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>0.780668</td>\n",
              "      <td>0.153232</td>\n",
              "      <td>0.814225</td>\n",
              "      <td>13.245517</td>\n",
              "      <td>25</td>\n",
              "      <td>0.920000</td>\n",
              "      <td>0.080000</td>\n",
              "      <td>0.013578</td>\n",
              "      <td>0.123191</td>\n",
              "      <td>4.351</td>\n",
              "      <td>2381</td>\n",
              "      <td>6</td>\n",
              "      <td>10</td>\n",
              "      <td>62</td>\n",
              "      <td>5327</td>\n",
              "      <td>9</td>\n",
              "      <td>11</td>\n",
              "      <td>85</td>\n",
              "      <td>6318</td>\n",
              "      <td>11</td>\n",
              "      <td>...</td>\n",
              "      <td>15205</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15205</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15207</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15210</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15211</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15212</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15215</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15217</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15217</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>21</td>\n",
              "      <td>29</td>\n",
              "      <td>169</td>\n",
              "      <td>15217</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1818</th>\n",
              "      <td>210277954204_10153191565724205</td>\n",
              "      <td>0.005307</td>\n",
              "      <td>0.192839</td>\n",
              "      <td>0.001432</td>\n",
              "      <td>0.213901</td>\n",
              "      <td>0.172704</td>\n",
              "      <td>0.000084</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.032940</td>\n",
              "      <td>0.380792</td>\n",
              "      <td>9</td>\n",
              "      <td>0.014046</td>\n",
              "      <td>0.398062</td>\n",
              "      <td>0.397978</td>\n",
              "      <td>409.310345</td>\n",
              "      <td>29</td>\n",
              "      <td>11870</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>1.749854</td>\n",
              "      <td>0.132556</td>\n",
              "      <td>0.519292</td>\n",
              "      <td>14.114150</td>\n",
              "      <td>29</td>\n",
              "      <td>0.931034</td>\n",
              "      <td>0.068966</td>\n",
              "      <td>0.001668</td>\n",
              "      <td>0.067481</td>\n",
              "      <td>3.431</td>\n",
              "      <td>7955</td>\n",
              "      <td>27</td>\n",
              "      <td>29</td>\n",
              "      <td>77</td>\n",
              "      <td>13488</td>\n",
              "      <td>39</td>\n",
              "      <td>47</td>\n",
              "      <td>120</td>\n",
              "      <td>16619</td>\n",
              "      <td>45</td>\n",
              "      <td>...</td>\n",
              "      <td>54434</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54441</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54452</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54469</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54483</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54488</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54492</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54503</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54513</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>135</td>\n",
              "      <td>136</td>\n",
              "      <td>368</td>\n",
              "      <td>54518</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1819</th>\n",
              "      <td>210277954204_10153191551594205</td>\n",
              "      <td>0.003012</td>\n",
              "      <td>0.006112</td>\n",
              "      <td>0.134367</td>\n",
              "      <td>0.277059</td>\n",
              "      <td>0.002834</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.001506</td>\n",
              "      <td>0.088220</td>\n",
              "      <td>0.048096</td>\n",
              "      <td>0.438795</td>\n",
              "      <td>9</td>\n",
              "      <td>0.018865</td>\n",
              "      <td>0.501860</td>\n",
              "      <td>0.500443</td>\n",
              "      <td>389.310345</td>\n",
              "      <td>29</td>\n",
              "      <td>11290</td>\n",
              "      <td>224</td>\n",
              "      <td>400</td>\n",
              "      <td>2.335628</td>\n",
              "      <td>0.122905</td>\n",
              "      <td>0.716386</td>\n",
              "      <td>12.977011</td>\n",
              "      <td>30</td>\n",
              "      <td>0.766667</td>\n",
              "      <td>0.233333</td>\n",
              "      <td>0.003620</td>\n",
              "      <td>0.040390</td>\n",
              "      <td>4.078</td>\n",
              "      <td>2204</td>\n",
              "      <td>76</td>\n",
              "      <td>11</td>\n",
              "      <td>126</td>\n",
              "      <td>4365</td>\n",
              "      <td>109</td>\n",
              "      <td>15</td>\n",
              "      <td>182</td>\n",
              "      <td>5453</td>\n",
              "      <td>134</td>\n",
              "      <td>...</td>\n",
              "      <td>29754</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29775</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29792</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29802</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29810</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29819</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29827</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29831</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29836</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>638</td>\n",
              "      <td>49</td>\n",
              "      <td>775</td>\n",
              "      <td>29841</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>1820 rows × 702 columns</p>\n",
              "</div>"
            ],
            "text/plain": [
              "                     facebook_post_id  ...  views.168\n",
              "0     407570359384477_612049142269930  ...     351137\n",
              "1     407570359384477_612108412264003  ...      88149\n",
              "2     407570359384477_612000682274776  ...     116597\n",
              "3     407570359384477_612254708916040  ...   18655415\n",
              "4     407570359384477_612167392258105  ...     436438\n",
              "...                               ...  ...        ...\n",
              "1815   210277954204_10153191547364205  ...      17044\n",
              "1816   210277954204_10153191554684205  ...      68636\n",
              "1817   210277954204_10153191559204205  ...      15217\n",
              "1818   210277954204_10153191565724205  ...      54518\n",
              "1819   210277954204_10153191551594205  ...      29841\n",
              "\n",
              "[1820 rows x 702 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 4
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "p3bTd_tWHdRp",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "#  DATA SELECTOR\n",
        "\n",
        "x_train = data.iloc[0:100,1:701].values\n",
        "x_test = data.iloc[101:150,1:701].values\n",
        "\n",
        "y_train = data.iloc[0:100,701].values\n",
        "y_test = data.iloc[101:150,701].values"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "jh9osYLkHdOr",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "y_train = y_train.ravel()\n",
        "y_test = y_test.ravel()"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "vbUN0AyTHdLe",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "from sklearn.preprocessing import StandardScaler\n",
        "\n",
        "sc_x = StandardScaler()\n",
        "sc_y = StandardScaler()\n",
        "x_tr = sc_x.fit_transform(x_train)\n",
        "x_te = sc_x.fit_transform(x_test)\n",
        "y_tr = sc_y.fit_transform(y_train.reshape(-1,1)).ravel()\n",
        "y_te = sc_y.fit_transform(y_test.reshape(-1,1)).ravel()"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "lT1Gy28oHdHb",
        "colab_type": "code",
        "outputId": "80e1e847-373c-44c2-e1b9-bb5de3681265",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        }
      },
      "source": [
        "x_tr.shape"
      ],
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(100, 700)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 8
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "gG3aFzn7Hy7t",
        "colab_type": "code",
        "outputId": "9bdce580-02e2-4f80-9388-c05c4d240b15",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        }
      },
      "source": [
        "y_tr.shape"
      ],
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(100,)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Yzf3KqpfHy5N",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "\"\"\"Using Libraly\"\"\"\n",
        "\n",
        "import numpy as np\n",
        "import random\n",
        "from itertools import combinations as cb\n",
        "import math\n",
        "from copy import deepcopy as dc\n",
        "from tqdm import tqdm\n",
        "from sklearn import svm  \n",
        "from sklearn import model_selection as ms\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "gaigM5h2Hy2U",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "\"\"\"Evaluate Function \"\"\"\n",
        "class Evaluate:\n",
        "    def __init__(self):\n",
        "        None\n",
        "    def evaluate(self,gen):\n",
        "        None\n",
        "    def check_dimentions(self,dim):\n",
        "        None"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "wMOYj4XiIPNd",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "\"\"\"Common Function\"\"\"\n",
        "def random_search(n,dim):\n",
        "    \"\"\"\n",
        "    create genes list\n",
        "    input:{ n: Number of population, default=20\n",
        "            dim: Number of dimension\n",
        "    }\n",
        "    output:{genes_list → [[0,0,0,1,1,0,1,...]...n]\n",
        "    }\n",
        "    \"\"\"\n",
        "    gens=[[0 for g in range(dim)] for _ in range(n)]\n",
        "    for i,gen in enumerate(gens) :\n",
        "        r=random.randint(1,dim)\n",
        "        for _r in range(r):\n",
        "            gen[_r]=1\n",
        "        random.shuffle(gen)\n",
        "    return gens\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "40fYYa8BIPKv",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "\"\"\"BBA\"\"\"\n",
        "def BBA(Eval_Func,n=20,m_i=200,dim=None,minf=0,prog=False,qmin=0,qmax=2,loud_A=0.25,r=0.4):\n",
        "    \"\"\"\n",
        "    input:{ Eval_Func: Evaluate_Function, type is class\n",
        "            n: Number of population, default=20\n",
        "            m_i: Number of max iteration, default=300\n",
        "            minf: minimazation flag, default=0, 0=maximization, 1=minimazation\n",
        "            dim: Number of feature, default=None\n",
        "            prog: Do you want to use a progress bar?, default=False\n",
        "            qmin: frequency minimum to step\n",
        "            qmax: frequency maximum to step\n",
        "            loud_A: value of Loudness, default=0.25\n",
        "            r: Pulse rate, default=0.4, Probability to relocate near the best position\n",
        "            }\n",
        "    output:{Best value: type float 0.967\n",
        "            Best position: type list(int) [1,0,0,1,.....]\n",
        "            Nunber of 1s in best position: type int [0,1,1,0,1] → 3\n",
        "            }\n",
        "    \"\"\"\n",
        "    estimate=Eval_Func().evaluate\n",
        "    if dim==None:\n",
        "        dim=Eval_Func().check_dimentions(dim)\n",
        "    #flag=dr\n",
        "    #qmin=0\n",
        "    #qmax=2\n",
        "    #loud_A=0.25\n",
        "    #r=0.1\n",
        "    #n_iter=0\n",
        "    gens_dic={tuple([0]*dim):float(\"-inf\") if minf == 0 else float(\"inf\")}\n",
        "    q=[0 for i in range(n)]\n",
        "    v=[[0 for d in range(dim)] for i in range(n)]\n",
        "    #cgc=[0 for i in range(max_iter)]\n",
        "    fit=[float(\"-inf\") if minf == 0 else float(\"inf\") for i in range(n)]\n",
        "    #dr=False\n",
        "    gens=random_search(n,dim)#[[random.choice([0,1]) for d in range(dim)] for i in range(n)]\n",
        "\n",
        "    for i in range(n):\n",
        "        if  tuple(gens[i]) in gens_dic:\n",
        "            fit[i]=gens_dic[tuple(gens[i])]\n",
        "        else:\n",
        "            fit[i]=estimate(gens[i])\n",
        "            gens_dic[tuple(gens[i])]=fit[i]\n",
        "\n",
        "    if minf==0:\n",
        "        maxf=max(fit)\n",
        "        best_v=maxf\n",
        "        best_s=gens[fit.index(max(fit))]\n",
        "    elif minf==1:\n",
        "        minf=min(fit)\n",
        "        best_v=minf\n",
        "        best_s=gens[fit.index(min(fit))]\n",
        "\n",
        "\n",
        "    if prog:\n",
        "        miter=tqdm(range(m_i))\n",
        "    else:\n",
        "        miter=range(m_i)\n",
        "\n",
        "    for it in miter:\n",
        "        #cgc[i]=maxf\n",
        "        for i in range(n):\n",
        "            for j in range(dim):\n",
        "                q[i]=qmin+(qmin-qmax)*random.random()\n",
        "                v[i][j]=v[i][j]+(gens[i][j]-best_s[j])*q[i]\n",
        "\n",
        "                vstf=abs((2/math.pi)*math.atan((math.pi/2)*v[i][j]))\n",
        "\n",
        "                if random.random()<vstf:\n",
        "                    gens[i][j]= 0 if gens[i][j]==1 else 1\n",
        "                else:\n",
        "                    pass\n",
        "\n",
        "                if random.random()>r:\n",
        "                    gens[i][j]=best_s[j]\n",
        "\n",
        "            if  tuple(gens[i]) in gens_dic:\n",
        "                fnew=gens_dic[tuple(gens[i])]\n",
        "            else:\n",
        "                fnew=estimate(gens[i])\n",
        "                gens_dic[tuple(gens[i])]=fnew\n",
        "\n",
        "            if fnew >= fit[i] and random.random() < loud_A if minf==0 else fnew <= fit[i] and random.random() < loud_A:#max?\n",
        "                gens[i]=gens[i]\n",
        "                fit[i]=fnew\n",
        "\n",
        "            if fnew>best_v if minf==0 else fnew<best_v:\n",
        "                best_s=dc(gens[i])\n",
        "                best_v=dc(fnew)\n",
        "\n",
        "    return best_v,best_s,best_s.count(1)\n"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "AdiAVOy9IOT1",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "class Evaluate:\n",
        "    def __init__(self):\n",
        "        self.train_label = y_tr\n",
        "        self.train_data = x_tr\n",
        "        self.test_label = y_te\n",
        "        self.test_data = x_te\n",
        "        self.K = 4\n",
        "    def evaluate(self,gen):\n",
        "        mask=np.array(gen) > 0\n",
        "        al_data=np.array([al[mask] for al in self.train_data])\n",
        "        al_test_data=np.array([al[mask] for al in self.test_data])\n",
        "        kf = ms.KFold(n_splits=self.K)\n",
        "        s = 0\n",
        "        for tr_ix,te_ix in kf.split(al_data):\n",
        "          clf = svm.SVR()\n",
        "          clf = clf.fit(al_data[tr_ix],self.train_label[tr_ix])\n",
        "          s+=clf.score(al_data[te_ix],self.train_label[te_ix])\n",
        "        s/=self.K\n",
        "        return s   #np.count_nonzero(self.test_l==res)/len(self.test_l)\n",
        "    def check_dimentions(self,dim):\n",
        "        if dim==None:\n",
        "            return len(self.train_d[0])\n",
        "        else:\n",
        "            return dim"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "DMwZBqhNIOQ3",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "def test_score(gen,tr_x,tr_y,te_x,te_y):\n",
        "    clf = svm.SVR()\n",
        "    mask=np.array(gen) == 1\n",
        "    al_data=np.array(x_tr[:,mask])\n",
        "    al_test_data=np.array(x_te[:,mask])\n",
        "    return np.mean([SVR.fit(al_data,y_tr).score(al_test_data,y_te) for i in range(4)])"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "2ePeHmzaJPEw",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "Bs,Bg,Bl=BBA(Eval_Func=Evaluate,n=len(x_tr[0:]),m_i=200, dim = len(x_tr[0]) ,minf = 0 )"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "7A-324eOJPBi",
        "colab_type": "code",
        "outputId": "dd6bb113-7793-4dd9-c7cd-f0f0589145ab",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        }
      },
      "source": [
        "Bs"
      ],
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "0.7724906199192234"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "yxQMQ1YhJO-E",
        "colab_type": "code",
        "outputId": "5e28bdb4-880b-4884-a099-3ca98cfb7a3d",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        }
      },
      "source": [
        "Bl"
      ],
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "222"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 18
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Ag0cnAdHIONW",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "BG = np.asarray(Bg)"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Mi5ShDC7KiZ8",
        "colab_type": "code",
        "outputId": "9f6cb329-99bc-468f-9082-9d14a309fcfb",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 585
        }
      },
      "source": [
        "BG.reshape(1,700)"
      ],
      "execution_count": 20,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,\n",
              "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
              "        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
              "        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,\n",
              "        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,\n",
              "        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,\n",
              "        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,\n",
              "        1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,\n",
              "        1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,\n",
              "        0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,\n",
              "        1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,\n",
              "        0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,\n",
              "        1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,\n",
              "        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,\n",
              "        0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,\n",
              "        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,\n",
              "        1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,\n",
              "        0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,\n",
              "        0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,\n",
              "        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,\n",
              "        0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,\n",
              "        0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,\n",
              "        0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,\n",
              "        1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,\n",
              "        0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,\n",
              "        1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,\n",
              "        0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,\n",
              "        1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,\n",
              "        0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,\n",
              "        0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,\n",
              "        0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,\n",
              "        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]])"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 20
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "TEYKeXwYL_Mw",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 585
        },
        "outputId": "253dbfe4-5bba-4be7-c236-185ec5e43b45"
      },
      "source": [
        "BG"
      ],
      "execution_count": 21,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,\n",
              "       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
              "       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,\n",
              "       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,\n",
              "       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,\n",
              "       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,\n",
              "       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,\n",
              "       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,\n",
              "       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,\n",
              "       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,\n",
              "       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,\n",
              "       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,\n",
              "       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,\n",
              "       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,\n",
              "       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,\n",
              "       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,\n",
              "       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,\n",
              "       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,\n",
              "       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,\n",
              "       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,\n",
              "       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,\n",
              "       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,\n",
              "       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,\n",
              "       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,\n",
              "       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,\n",
              "       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,\n",
              "       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,\n",
              "       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,\n",
              "       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,\n",
              "       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,\n",
              "       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,\n",
              "       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 21
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "NWwS8pgCMMoW",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "lst = []\n",
        "for i in range(len(BG)):\n",
        "  if BG[i] == 0:\n",
        "    lst.append(list(data.columns)[i])\n",
        "\n",
        "ans = data.drop(lst,axis=1)\n",
        "\n",
        "ans.to_csv('after_bat.csv', index=False)\n",
        "from google.colab import files\n",
        "\n",
        "files.download('after_bat.csv')"
      ],
      "execution_count": 0,
      "outputs": []
    }
  ]
}